// <auto-generated />
using System;
using ControlMareas.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlMareas.App.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520235815_AddFechaFinColumn")]
    partial class AddFechaFinColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ControlMareas.App.Data.Entities.AuditoriaMareaLote", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("Fecha");

                    b.Property<string>("MareaID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MareaID");

                    b.Property<string>("Metadatos")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadatos");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Resultado");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tipo");

                    b.HasKey("ID");

                    b.HasIndex("MareaID")
                        .HasDatabaseName("ix_auditoria_mareas_lotes_marea_id");

                    b.ToTable("auditoria_mareas_lotes", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.AuditoriaMareaRegistro", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Entidad")
                        .HasColumnType("TEXT")
                        .HasColumnName("Entidad");

                    b.Property<string>("EntidadID")
                        .HasColumnType("TEXT")
                        .HasColumnName("EntidadID");

                    b.Property<string>("LoteID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LoteID");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Mensaje");

                    b.Property<string>("Metadatos")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadatos");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nivel");

                    b.HasKey("ID");

                    b.HasIndex("LoteID")
                        .HasDatabaseName("ix_auditoria_mareas_registros_lote_id");

                    b.ToTable("auditoria_mareas_registros", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Buque", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<int?>("IMO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IMO");

                    b.Property<int>("IdRadial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdRadial");

                    b.Property<int?>("MMSI")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MMSI");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Matricula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdRadial");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("buques", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Especie", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoInidep")
                        .HasColumnType("TEXT")
                        .HasColumnName("CodigoInidep");

                    b.Property<string>("DocumentoInformativo")
                        .HasColumnType("TEXT")
                        .HasColumnName("DocumentoInformativo");

                    b.Property<string>("Especifico")
                        .HasColumnType("TEXT")
                        .HasColumnName("Especifico");

                    b.Property<string>("Familia")
                        .HasColumnType("TEXT")
                        .HasColumnName("Familia");

                    b.Property<int>("Frecuente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Frecuente");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT")
                        .HasColumnName("Genero");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreCientifico");

                    b.Property<string>("NombreVulgar")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreVulgar");

                    b.Property<string>("Orden")
                        .HasColumnType("TEXT")
                        .HasColumnName("Orden");

                    b.HasKey("ID");

                    b.HasIndex("CodigoInidep")
                        .IsUnique()
                        .HasDatabaseName("ix_especies_codigo_inidep");

                    b.ToTable("especies", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.EspecieLargoPeso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("EspecieId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieID");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("Observaciones");

                    b.Property<double>("ParamA")
                        .HasColumnType("REAL")
                        .HasColumnName("ParamA");

                    b.Property<double>("ParamB")
                        .HasColumnType("REAL")
                        .HasColumnName("ParamB");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sexo");

                    b.Property<string>("TipoMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("TipoMedida");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId", "Sexo")
                        .HasDatabaseName("ix_especies_largo_peso_especie_sexo");

                    b.ToTable("especies_largo_peso", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.EspecieVieja", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoInidep")
                        .HasColumnType("TEXT")
                        .HasColumnName("CodigoInidep");

                    b.Property<string>("DocumentoInformativo")
                        .HasColumnType("TEXT")
                        .HasColumnName("DocumentoInformativo");

                    b.Property<string>("Especifico")
                        .HasColumnType("TEXT")
                        .HasColumnName("Especifico");

                    b.Property<string>("Familia")
                        .HasColumnType("TEXT")
                        .HasColumnName("Familia");

                    b.Property<int>("Frecuente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Frecuente");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT")
                        .HasColumnName("Genero");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreCientifico");

                    b.Property<string>("NombreVulgar")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreVulgar");

                    b.Property<string>("Orden")
                        .HasColumnType("TEXT")
                        .HasColumnName("Orden");

                    b.HasKey("ID");

                    b.HasIndex("CodigoInidep")
                        .IsUnique()
                        .HasDatabaseName("ix_especies_viejas_codigo_inidep");

                    b.ToTable("especies_viejas", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.FrecuenciaTalla", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<string>("MuestraID")
                        .HasColumnType("TEXT")
                        .HasColumnName("MuestraID");

                    b.Property<int>("NroHembras")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroHembras");

                    b.Property<int>("NroIndeterminados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroIndeterminados");

                    b.Property<int>("NroLangostinosHembraImpregnadas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroLangostinosHembraImpregnadas");

                    b.Property<int>("NroLangostinosHembraMaduras")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroLangostinosHembraMaduras");

                    b.Property<int>("NroLangostinosMachoMaduros")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroLangostinosMachoMaduros");

                    b.Property<int>("NroMachos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroMachos");

                    b.Property<int>("NroTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroTotal");

                    b.Property<double>("Talla")
                        .HasColumnType("REAL")
                        .HasColumnName("Talla");

                    b.HasKey("ID");

                    b.HasIndex("MuestraID")
                        .HasDatabaseName("ix_frecuencias_de_tallas_muestra_id");

                    b.ToTable("frecuencias_de_tallas", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.FrecuenciaTallaEstadio", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("EstadiosHembras")
                        .HasColumnType("TEXT")
                        .HasColumnName("EstadiosHembras");

                    b.Property<string>("EstadiosMachos")
                        .HasColumnType("TEXT")
                        .HasColumnName("EstadiosMachos");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<string>("MuestraID")
                        .HasColumnType("TEXT")
                        .HasColumnName("MuestraID");

                    b.Property<int>("NroIndeterminados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroIndeterminados");

                    b.Property<double>("Talla")
                        .HasColumnType("REAL")
                        .HasColumnName("Talla");

                    b.HasKey("ID");

                    b.HasIndex("MuestraID")
                        .HasDatabaseName("ix_frecuencias_de_tallas_con_estadio_muestra_id");

                    b.ToTable("frecuencias_de_tallas_con_estadio", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemCaptura", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<double>("DatoCaptura")
                        .HasColumnType("REAL")
                        .HasColumnName("DatoCaptura");

                    b.Property<double>("DatoDescarte")
                        .HasColumnType("REAL")
                        .HasColumnName("DatoDescarte");

                    b.Property<string>("EspecieID")
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieID");

                    b.Property<string>("EspecieOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieOriginal");

                    b.Property<string>("LanceID")
                        .HasColumnType("TEXT")
                        .HasColumnName("LanceID");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumeroOrden");

                    b.Property<int>("TipoDatoCaptura")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoDatoCaptura");

                    b.Property<int>("TipoDatoDescarte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoDatoDescarte");

                    b.HasKey("ID");

                    b.HasIndex("EspecieID")
                        .HasDatabaseName("ix_items_captura_especie_id");

                    b.HasIndex("LanceID")
                        .HasDatabaseName("ix_items_captura_lance_id");

                    b.ToTable("items_captura", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemContenidoGastrico", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<int>("CantPiezas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CantPiezas");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comentarios");

                    b.Property<int>("Grupo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Grupo");

                    b.Property<string>("ItemSubmuestraID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ItemSubmuestraID");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<double>("Porcentaje")
                        .HasColumnType("REAL")
                        .HasColumnName("Porcentaje");

                    b.HasKey("ID");

                    b.HasIndex("ItemSubmuestraID")
                        .HasDatabaseName("ix_item_contenido_gastrico_item_submuestra_id");

                    b.ToTable("item_contenido_gastrico", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemSubmuestra", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<double?>("Area")
                        .HasColumnType("REAL");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comentarios");

                    b.Property<double?>("Edad")
                        .HasColumnType("REAL")
                        .HasColumnName("Edad");

                    b.Property<string>("EspecieOriginal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Estadio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Estadio");

                    b.Property<double?>("Fuente")
                        .HasColumnType("REAL");

                    b.Property<int?>("LargoEstandarMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LargoEstandarMm");

                    b.Property<int?>("LargoTotalMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LargoTotalMm");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<string>("MuestraID")
                        .HasColumnType("TEXT")
                        .HasColumnName("MuestraID");

                    b.Property<int>("NroEjemplar")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroEjemplar");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PesoGon")
                        .HasColumnType("REAL");

                    b.Property<double?>("PesoHig")
                        .HasColumnType("REAL");

                    b.Property<double?>("PesoTotalGramos")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoTotalGramos");

                    b.Property<double?>("PesoVac")
                        .HasColumnType("REAL");

                    b.Property<double?>("RTotal")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReplecionGastrica")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReplecionGastrica");

                    b.Property<int?>("Sexo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sexo");

                    b.Property<double?>("Tarte")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("Estadio")
                        .HasDatabaseName("ix_items_submuestras_estadio");

                    b.HasIndex("MuestraID")
                        .HasDatabaseName("ix_items_submuestras_muestra_id");

                    b.HasIndex("Sexo")
                        .HasDatabaseName("ix_items_submuestras_sexo");

                    b.ToTable("items_submuestras", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Lance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("AberturaVerticalM")
                        .HasColumnType("REAL")
                        .HasColumnName("abertura_vertical_m");

                    b.Property<double?>("AreaBarrida")
                        .HasColumnType("REAL");

                    b.Property<double?>("ArteNro")
                        .HasColumnType("REAL");

                    b.Property<double?>("ArteTipo")
                        .HasColumnType("REAL");

                    b.Property<int?>("CableFiladoM")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cable_filado_m");

                    b.Property<double?>("CapturaTotalKg")
                        .HasColumnType("REAL")
                        .HasColumnName("captura_total_kg");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("comentarios");

                    b.Property<double?>("DescarteTotalKg")
                        .HasColumnType("REAL")
                        .HasColumnName("descarte_total_kg");

                    b.Property<double?>("DistanciaAlasM")
                        .HasColumnType("REAL")
                        .HasColumnName("distancia_alas_m");

                    b.Property<double?>("DistanciaPortonesM")
                        .HasColumnType("REAL")
                        .HasColumnName("distancia_portones_m");

                    b.Property<double?>("EdadLuna")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstacionGral")
                        .HasColumnType("REAL");

                    b.Property<int?>("EstadoMarCodigo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estado_mar_codigo");

                    b.Property<int?>("EstadoTiempoCodigo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estado_tiempo_codigo");

                    b.Property<double?>("Estrato")
                        .HasColumnType("REAL");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<string>("HoraFinal")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_final");

                    b.Property<string>("HoraInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<double?>("LatitudFinalDecimal")
                        .HasColumnType("REAL")
                        .HasColumnName("latitud_final_decimal");

                    b.Property<double?>("LatitudInicioDecimal")
                        .HasColumnType("REAL")
                        .HasColumnName("latitud_inicio_decimal");

                    b.Property<double?>("LongitudFinalDecimal")
                        .HasColumnType("REAL")
                        .HasColumnName("longitud_final_decimal");

                    b.Property<double?>("LongitudInicioDecimal")
                        .HasColumnType("REAL")
                        .HasColumnName("longitud_inicio_decimal");

                    b.Property<double?>("Luz")
                        .HasColumnType("REAL");

                    b.Property<int?>("MallaAlasMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("malla_alas_mm");

                    b.Property<int?>("MallaCopoMm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("malla_copo_mm");

                    b.Property<double?>("MallaSobre")
                        .HasColumnType("REAL");

                    b.Property<string>("MareaEtapaId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("marea_etapa_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<double?>("Mus")
                        .HasColumnType("REAL");

                    b.Property<int>("NroLance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nro_lance");

                    b.Property<int?>("PresionHpa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("presion_hpa");

                    b.Property<int?>("ProfundidadFinalM")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profundidad_final_m");

                    b.Property<int?>("ProfundidadInicioM")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profundidad_inicio_m");

                    b.Property<int?>("RumboGrados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rumbo_grados");

                    b.Property<int>("SelectividadSiNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selectividad_si_no");

                    b.Property<double?>("TemperaturaAireC")
                        .HasColumnType("REAL")
                        .HasColumnName("temperatura_aire_c");

                    b.Property<double?>("TemperaturaRedC")
                        .HasColumnType("REAL")
                        .HasColumnName("temperatura_red_c");

                    b.Property<double?>("TmpAHum")
                        .HasColumnType("REAL");

                    b.Property<double?>("TmpMarS")
                        .HasColumnType("REAL");

                    b.Property<double?>("VelocidadArrastreNudos")
                        .HasColumnType("REAL")
                        .HasColumnName("velocidad_arrastre_nudos");

                    b.Property<int?>("VientoDireccionGrados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("viento_direccion_grados");

                    b.Property<int?>("VientoFuerzaBeaufort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("viento_fuerza_beaufort");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("idx_lances_fecha");

                    b.HasIndex("MareaEtapaId")
                        .HasDatabaseName("idx_lances_marea_etapa_id");

                    b.HasIndex("MareaEtapaId", "NroLance")
                        .IsUnique();

                    b.ToTable("lances", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Marea", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<int>("AnioInidep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AnioInidep");

                    b.Property<string>("BuqueID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comentarios");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaInicio");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<int>("NumeroInidep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumeroInidep");

                    b.HasKey("ID");

                    b.HasIndex("BuqueID")
                        .HasDatabaseName("ix_mareas_buque_id");

                    b.ToTable("mareas", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.MareaEtapa", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<int?>("AnioMareaBuque")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AnioMareaBuque");

                    b.Property<string>("EspecieObjetivoID")
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieObjetivoID");

                    b.Property<DateTime?>("FechaArribo")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaArribo");

                    b.Property<DateTime>("FechaZarpada")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaZarpada");

                    b.Property<string>("MareaID")
                        .HasColumnType("TEXT")
                        .HasColumnName("MareaID");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<string>("NombreCapitan")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreCapitan");

                    b.Property<string>("NombreOficialCubierta")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreOficialCubierta");

                    b.Property<string>("NombreOficialPesca")
                        .HasColumnType("TEXT")
                        .HasColumnName("NombreOficialPesca");

                    b.Property<int?>("NumeroMareaBuque")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumeroMareaBuque");

                    b.HasKey("ID");

                    b.HasIndex("EspecieObjetivoID")
                        .HasDatabaseName("ix_marea_etapas_especie_objetivo_id");

                    b.HasIndex("MareaID")
                        .HasDatabaseName("ix_marea_etapas_marea_id");

                    b.ToTable("marea_etapas", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.MareaTracking", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("MareaID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Rumbo")
                        .HasColumnType("REAL");

                    b.Property<double>("Velocidad")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("MareaID");

                    b.ToTable("TrackingPoints");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Muestra", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<double?>("Area")
                        .HasColumnType("REAL")
                        .HasColumnName("Area");

                    b.Property<bool>("Automatica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("automatica");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comentarios");

                    b.Property<int>("DiscriminaSexo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DiscriminaSexo");

                    b.Property<int>("EjemplaresPorKg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EjemplaresPorKg");

                    b.Property<string>("EspecieID")
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieID");

                    b.Property<string>("EspecieOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieOriginal");

                    b.Property<double?>("FactPond")
                        .HasColumnType("REAL")
                        .HasColumnName("FactPond");

                    b.Property<double?>("Fuente")
                        .HasColumnType("REAL")
                        .HasColumnName("Fuente");

                    b.Property<int>("HayIndeterminados")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HayIndeterminados");

                    b.Property<double>("Intervalo")
                        .HasColumnType("REAL")
                        .HasColumnName("Intervalo");

                    b.Property<string>("LanceID")
                        .HasColumnType("TEXT")
                        .HasColumnName("LanceID");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<int>("ModoMedicionTalla")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ModoMedicionTalla");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumeroOrden");

                    b.Property<int>("Origen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Origen");

                    b.Property<double?>("PesoMuestra_PesoGramos")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoMuestra_PesoGramos");

                    b.Property<int?>("PrimTalla")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PrimTalla");

                    b.Property<double?>("Tarte")
                        .HasColumnType("REAL")
                        .HasColumnName("Tarte");

                    b.Property<int>("TipoMuestra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("TipoMuestra");

                    b.Property<int?>("UltTalla")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UltTalla");

                    b.Property<int>("UnidadMedidaTalla")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UnidadMedidaTalla");

                    b.HasKey("ID");

                    b.HasIndex("EspecieID")
                        .HasDatabaseName("ix_muestras_especie_id");

                    b.HasIndex("LanceID")
                        .HasDatabaseName("ix_muestras_lance_id");

                    b.ToTable("muestras", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.RegistroProduccion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("comentarios");

                    b.Property<string>("EspecieId")
                        .HasColumnType("TEXT")
                        .HasColumnName("especie_id");

                    b.Property<string>("EspecieOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("EspecieOriginal");

                    b.Property<double?>("Factor")
                        .HasColumnType("REAL")
                        .HasColumnName("factor_conversion");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("IdProducto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("id_producto");

                    b.Property<double?>("Kg")
                        .HasColumnType("REAL")
                        .HasColumnName("kg");

                    b.Property<string>("MareaEtapaId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("marea_etapa_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumeroOrden");

                    b.Property<int?>("Operarios")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operarios");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("idx_registros_produccion_fecha");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_registros_produccion_producto");

                    b.HasIndex("MareaEtapaId")
                        .HasDatabaseName("idx_registros_produccion_marea_etapa_id");

                    b.HasIndex("MareaEtapaId", "Fecha", "IdProducto", "Categoria")
                        .HasDatabaseName("idx_registros_produccion_unico_logico");

                    b.ToTable("registros_produccion", (string)null);
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.AuditoriaMareaLote", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Marea", "Marea")
                        .WithMany()
                        .HasForeignKey("MareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_mareas_lotes_mareas_marea_id");

                    b.Navigation("Marea");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.AuditoriaMareaRegistro", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.AuditoriaMareaLote", "Lote")
                        .WithMany("Registros")
                        .HasForeignKey("LoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_mareas_registros_lotes_lote_id");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.EspecieLargoPeso", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.FrecuenciaTalla", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Muestra", "Muestra")
                        .WithMany("FrecuenciasTallas")
                        .HasForeignKey("MuestraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_frecuencias_de_tallas_muestras_muestra_id");

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.FrecuenciaTallaEstadio", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Muestra", "Muestra")
                        .WithMany("FrecuenciasTallasEstadio")
                        .HasForeignKey("MuestraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_frecuencias_de_tallas_con_estadio_muestras_muestra_id");

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemCaptura", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Especie", "Especie")
                        .WithMany("ItemsCaptura")
                        .HasForeignKey("EspecieID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_items_captura_especies_especie_id");

                    b.HasOne("ControlMareas.App.Data.Entities.Lance", "Lance")
                        .WithMany("ItemsCaptura")
                        .HasForeignKey("LanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_items_captura_lances_lance_id");

                    b.Navigation("Especie");

                    b.Navigation("Lance");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemContenidoGastrico", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.ItemSubmuestra", "ItemSubmuestra")
                        .WithMany("ContenidosGastricos")
                        .HasForeignKey("ItemSubmuestraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_item_contenido_gastrico_items_submuestras_item_submuestra_id");

                    b.Navigation("ItemSubmuestra");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemSubmuestra", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Muestra", "Muestra")
                        .WithMany("ItemsSubmuestras")
                        .HasForeignKey("MuestraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_items_submuestras_muestras_muestra_id");

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Lance", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.MareaEtapa", "MareaEtapa")
                        .WithMany("Lances")
                        .HasForeignKey("MareaEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MareaEtapa");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Marea", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Buque", "Buque")
                        .WithMany("Mareas")
                        .HasForeignKey("BuqueID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mareas_buques_buque_id");

                    b.Navigation("Buque");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.MareaEtapa", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Especie", "EspecieObjetivo")
                        .WithMany("MareaEtapas")
                        .HasForeignKey("EspecieObjetivoID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_marea_etapas_especies_especie_objetivo_id");

                    b.HasOne("ControlMareas.App.Data.Entities.Marea", "Marea")
                        .WithMany("Etapas")
                        .HasForeignKey("MareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_marea_etapas_mareas_marea_id");

                    b.Navigation("EspecieObjetivo");

                    b.Navigation("Marea");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.MareaTracking", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Marea", "Marea")
                        .WithMany()
                        .HasForeignKey("MareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marea");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Muestra", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Especie", "Especie")
                        .WithMany("Muestras")
                        .HasForeignKey("EspecieID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_muestras_especies_especie_id");

                    b.HasOne("ControlMareas.App.Data.Entities.Lance", "Lance")
                        .WithMany("Muestras")
                        .HasForeignKey("LanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_muestras_lances_lance_id");

                    b.Navigation("Especie");

                    b.Navigation("Lance");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.RegistroProduccion", b =>
                {
                    b.HasOne("ControlMareas.App.Data.Entities.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlMareas.App.Data.Entities.Producto", "Producto")
                        .WithMany("RegistrosProduccion")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlMareas.App.Data.Entities.MareaEtapa", "MareaEtapa")
                        .WithMany("RegistrosProduccion")
                        .HasForeignKey("MareaEtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("MareaEtapa");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.AuditoriaMareaLote", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Buque", b =>
                {
                    b.Navigation("Mareas");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Especie", b =>
                {
                    b.Navigation("ItemsCaptura");

                    b.Navigation("MareaEtapas");

                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.ItemSubmuestra", b =>
                {
                    b.Navigation("ContenidosGastricos");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Lance", b =>
                {
                    b.Navigation("ItemsCaptura");

                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Marea", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.MareaEtapa", b =>
                {
                    b.Navigation("Lances");

                    b.Navigation("RegistrosProduccion");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Muestra", b =>
                {
                    b.Navigation("FrecuenciasTallas");

                    b.Navigation("FrecuenciasTallasEstadio");

                    b.Navigation("ItemsSubmuestras");
                });

            modelBuilder.Entity("ControlMareas.App.Data.Entities.Producto", b =>
                {
                    b.Navigation("RegistrosProduccion");
                });
#pragma warning restore 612, 618
        }
    }
}
